import { Users, Building2, Clock, FileCheck } from "lucide-react";
// Mock data
export const stats = [
  {
    label: "Tổng số TTTM/Thương hiệu đang hoạt động",
    value: "156",
    change: "+12%",
    icon: Building2,
    color: "bg-blue-500",
  },
  {
    label: "Tổng số nhân viên đang hoạt động",
    value: "24",
    change: "+3",
    icon: Users,
    color: "bg-green-500",
  },
  {
    label: "Tổng số yêu cầu xác thực đang chờ",
    value: "8",
    change: "-2",
    icon: Clock,
    color: "bg-yellow-500",
  },
  {
    label: "Tổng số hợp đồng trong tháng",
    value: "45",
    change: "+18%",
    icon: FileCheck,
    color: "bg-purple-500",
  },
];

export const mallsBrands = [
  {
    id: 1,
    name: "Vincom Center",
    type: "Mall",
    location: "District 1, HCMC",
    staff: "Nguyen Van A",
    status: "active",
    contracts: 5,
  },
  {
    id: 2,
    name: "Starbucks",
    type: "Brand",
    location: "Multiple",
    staff: "Tran Thi B",
    status: "active",
    contracts: 12,
  },
  {
    id: 3,
    name: "Lotte Mart",
    type: "Mall",
    location: "District 7, HCMC",
    staff: "Nguyen Van A",
    status: "active",
    contracts: 8,
  },
  {
    id: 4,
    name: "The Coffee House",
    type: "Brand",
    location: "Nationwide",
    staff: "Le Van C",
    status: "inactive",
    contracts: 3,
  },
];

export const areaAssignments = [
  {
    area: "Ho Chi Minh City",
    staff: ["Nguyen Van A", "Pham Van E"],
    malls: 45,
    brands: 67,
  },
  { area: "Hanoi", staff: ["Tran Thi B"], malls: 32, brands: 54 },
  { area: "Da Nang", staff: ["Le Van C"], malls: 18, brands: 28 },
  { area: "Can Tho", staff: ["Pham Thi D"], malls: 12, brands: 19 },
];
export const pendingVerifications = [
  {
    id: 1,
    name: "Vincom Center",
    type: "Mall",
    location: "District 1, HCMC",
    date: "2025-10-12",
    staff: "Nguyen Van A",
    status: "Pending",
  },
  {
    id: 2,
    name: "Starbucks",
    type: "Brand",
    location: "District 3, HCMC",
    date: "2025-10-13",
    staff: "Tran Thi B",
    status: "Pending",
  },
  {
    id: 3,
    name: "Aeon Mall",
    type: "Mall",
    location: "District 7, HCMC",
    date: "2025-10-14",
    staff: "Le Van C",
    status: "Approved",
  },
  {
    id: 4,
    name: "The Coffee House",
    type: "Brand",
    location: "District 5, HCMC",
    staff: null,
    date: "2025-10-15",
    status: "Rejected",
  },
];

export const monthlyContractsData = [
  { month: "Jan", contracts: 5, revenue: 450 },
  { month: "Feb", contracts: 8, revenue: 600 },
  { month: "Mar", contracts: 12, revenue: 900 },
  { month: "Apr", contracts: 7, revenue: 520 },
  { month: "May", contracts: 10, revenue: 750 },
  { month: "Jun", contracts: 15, revenue: 1100 },
];

export const quarterlyContractsData = [
  { quarter: "Q1", contracts: 25, revenue: 1950 },
  { quarter: "Q2", contracts: 32, revenue: 2400 },
  { quarter: "Q3", contracts: 34, revenue: 2550 },
  { quarter: "Q4", contracts: 29, revenue: 2100 },
];
export const matchingData = [
  {
    id: "1",
    mallName: "Vincom Center",
    brandName: "Nike",
    location: "HCM",
    matchScore: 85,
    date: "2025-10-15",
  },
  {
    id: "2",
    mallName: "AEON Mall",
    brandName: "Adidas",
    location: "HCM",
    matchScore: 72,
    date: "2025-10-14",
  },
  {
    id: "3",
    mallName: "Takashimaya",
    brandName: "Puma",
    location: "HCM",
    matchScore: 90,
    date: "2025-10-13",
  },
  {
    id: "4",
    mallName: "Vincom Mega Mall",
    brandName: "Reebok",
    location: "HCM",
    matchScore: 78,
    date: "2025-10-12",
  },
];
export const defaultWeights = {
  location: 0.4,
  brandPopularity: 0.3,
  mallTraffic: 0.2,
  rentalCost: 0.1,
};
interface Contract {
  coordination_contract_id: string;
  starting_date: string;
  ending_date: string;
  commision_percent: number;
  mall_owner: string;
  upload_by: string;
  create_at: string;
  terminated_at?: string;
  status: "Active" | "Pending" | "Terminated";
  update_by?: string;
  note?: string;
  contract_url?: string;
}
export const contracts: Contract[] = [
  {
    coordination_contract_id: "CT001",
    starting_date: "2024-06-01",
    ending_date: "2025-06-01",
    commision_percent: 10,
    mall_owner: "Vincom Đồng Khởi",
    upload_by: "Admin",
    create_at: "2024-06-01",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT002",
    starting_date: "2024-09-01",
    ending_date: "2025-09-01",
    commision_percent: 8,
    mall_owner: "Aeon Mall Tân Phú",
    upload_by: "Admin",
    create_at: "2024-09-01",
    status: "Pending",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT003",
    starting_date: "2024-10-15",
    ending_date: "2025-10-15",
    commision_percent: 12,
    mall_owner: "Crescent Mall",
    upload_by: "Admin",
    create_at: "2024-10-15",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT004",
    starting_date: "2024-11-01",
    ending_date: "2025-11-01",
    commision_percent: 7,
    mall_owner: "Saigon Centre",
    upload_by: "Admin",
    create_at: "2024-11-01",
    status: "Terminated",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT005",
    starting_date: "2025-01-01",
    ending_date: "2026-01-01",
    commision_percent: 9,
    mall_owner: "Diamond Plaza",
    upload_by: "Admin",
    create_at: "2025-01-01",
    status: "Active",
    contract_url: "#",
  },
  // 15 record mới
  {
    coordination_contract_id: "CT006",
    starting_date: "2025-02-01",
    ending_date: "2026-02-01",
    commision_percent: 11,
    mall_owner: "Lotte Mart Quận 7",
    upload_by: "Admin",
    create_at: "2025-02-01",
    status: "Pending",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT007",
    starting_date: "2025-03-15",
    ending_date: "2026-03-15",
    commision_percent: 6,
    mall_owner: "Takashimaya",
    upload_by: "Admin",
    create_at: "2025-03-15",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT008",
    starting_date: "2025-04-01",
    ending_date: "2026-04-01",
    commision_percent: 8,
    mall_owner: "Vivo City",
    upload_by: "Admin",
    create_at: "2025-04-01",
    status: "Terminated",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT009",
    starting_date: "2025-05-10",
    ending_date: "2026-05-10",
    commision_percent: 9,
    mall_owner: "Aeon Mall Bình Tân",
    upload_by: "Admin",
    create_at: "2025-05-10",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT010",
    starting_date: "2025-06-01",
    ending_date: "2026-06-01",
    commision_percent: 10,
    mall_owner: "Saigon Paragon",
    upload_by: "Admin",
    create_at: "2025-06-01",
    status: "Pending",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT011",
    starting_date: "2025-06-15",
    ending_date: "2026-06-15",
    commision_percent: 7,
    mall_owner: "Bitexco Tower Mall",
    upload_by: "Admin",
    create_at: "2025-06-15",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT012",
    starting_date: "2025-07-01",
    ending_date: "2026-07-01",
    commision_percent: 12,
    mall_owner: "Vincom Mega Mall Thảo Điền",
    upload_by: "Admin",
    create_at: "2025-07-01",
    status: "Terminated",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT013",
    starting_date: "2025-07-20",
    ending_date: "2026-07-20",
    commision_percent: 9,
    mall_owner: "The Garden Mall",
    upload_by: "Admin",
    create_at: "2025-07-20",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT014",
    starting_date: "2025-08-01",
    ending_date: "2026-08-01",
    commision_percent: 8,
    mall_owner: "Vincom Center Landmark 81",
    upload_by: "Admin",
    create_at: "2025-08-01",
    status: "Pending",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT015",
    starting_date: "2025-08-15",
    ending_date: "2026-08-15",
    commision_percent: 10,
    mall_owner: "Crescent Mall 2",
    upload_by: "Admin",
    create_at: "2025-08-15",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT016",
    starting_date: "2025-09-01",
    ending_date: "2026-09-01",
    commision_percent: 11,
    mall_owner: "AEON Mall Long Biên",
    upload_by: "Admin",
    create_at: "2025-09-01",
    status: "Terminated",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT017",
    starting_date: "2025-09-15",
    ending_date: "2026-09-15",
    commision_percent: 7,
    mall_owner: "Vincom Plaza Nguyễn Chí Thanh",
    upload_by: "Admin",
    create_at: "2025-09-15",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT018",
    starting_date: "2025-10-01",
    ending_date: "2026-10-01",
    commision_percent: 9,
    mall_owner: "Indochina Plaza",
    upload_by: "Admin",
    create_at: "2025-10-01",
    status: "Pending",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT019",
    starting_date: "2025-10-20",
    ending_date: "2026-10-20",
    commision_percent: 10,
    mall_owner: "Parkson Saigon Tourist",
    upload_by: "Admin",
    create_at: "2025-10-20",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT020",
    starting_date: "2025-11-01",
    ending_date: "2026-11-01",
    commision_percent: 8,
    mall_owner: "Vincom Plaza Cộng Hòa",
    upload_by: "Admin",
    create_at: "2025-11-01",
    status: "Terminated",
    contract_url: "#",
  },
];

// src/utils/data.ts
export interface Staff {
  id: string;
  name: string;
  area: string;
  contracts: number;
  revenue: number; // tổng doanh thu VND
  rating: number; // 1-5
  month: string; // "2025-10"
  status: "Active" | "Inactive";
  totalContracts: number; // tổng hợp đồng từ khi join
}

export const staffPerformance: Staff[] = [
  {
    id: "S001",
    name: "Nguyen Van A",
    area: "Quận 1",
    contracts: 5,
    totalContracts: 20,
    revenue: 12000000,
    rating: 4.8,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S002",
    name: "Tran Thi B",
    area: "Quận 3",
    contracts: 3,
    totalContracts: 10,
    revenue: 9500000,
    rating: 4.5,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S003",
    name: "Le Van C",
    area: "Quận 5",
    contracts: 6,
    totalContracts: 18,
    revenue: 13000000,
    rating: 4.9,
    status: "Inactive",
    month: "2025-10",
  },
  {
    id: "S004",
    name: "Pham Thi D",
    area: "Quận 7",
    contracts: 4,
    totalContracts: 12,
    revenue: 8500000,
    rating: 4.2,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S005",
    name: "Hoang Van E",
    area: "Quận 2",
    contracts: 7,
    totalContracts: 25,
    revenue: 15000000,
    rating: 5.0,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S006",
    name: "Vu Thi F",
    area: "Quận 9",
    contracts: 2,
    totalContracts: 8,
    revenue: 6000000,
    rating: 4.0,
    status: "Inactive",
    month: "2025-10",
  },
  {
    id: "S007",
    name: "Nguyen Van G",
    area: "Quận 4",
    contracts: 5,
    totalContracts: 15,
    revenue: 11000000,
    rating: 4.6,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S008",
    name: "Tran Thi H",
    area: "Quận 6",
    contracts: 3,
    totalContracts: 9,
    revenue: 9000000,
    rating: 4.3,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S009",
    name: "Le Van I",
    area: "Quận 8",
    contracts: 6,
    totalContracts: 19,
    revenue: 12500000,
    rating: 4.7,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S010",
    name: "Pham Thi J",
    area: "Quận 10",
    contracts: 4,
    totalContracts: 11,
    revenue: 8000000,
    rating: 4.1,
    status: "Inactive",
    month: "2025-10",
  },
  {
    id: "S011",
    name: "Hoang Van K",
    area: "Quận 11",
    contracts: 5,
    totalContracts: 14,
    revenue: 11500000,
    rating: 4.6,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S012",
    name: "Vu Thi L",
    area: "Quận 12",
    contracts: 3,
    totalContracts: 10,
    revenue: 9500000,
    rating: 4.4,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S013",
    name: "Nguyen Van M",
    area: "Quận 1",
    contracts: 7,
    totalContracts: 21,
    revenue: 15500000,
    rating: 5.0,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S014",
    name: "Tran Thi N",
    area: "Quận 3",
    contracts: 2,
    totalContracts: 7,
    revenue: 6500000,
    rating: 3.9,
    status: "Inactive",
    month: "2025-10",
  },
  {
    id: "S015",
    name: "Le Van O",
    area: "Quận 5",
    contracts: 4,
    totalContracts: 13,
    revenue: 8700000,
    rating: 4.2,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S016",
    name: "Pham Thi P",
    area: "Quận 7",
    contracts: 6,
    totalContracts: 17,
    revenue: 14000000,
    rating: 4.8,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S017",
    name: "Hoang Van Q",
    area: "Quận 2",
    contracts: 3,
    totalContracts: 12,
    revenue: 9500000,
    rating: 4.4,
    status: "Inactive",
    month: "2025-10",
  },
  {
    id: "S018",
    name: "Vu Thi R",
    area: "Quận 9",
    contracts: 5,
    totalContracts: 15,
    revenue: 11500000,
    rating: 4.7,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S019",
    name: "Nguyen Van S",
    area: "Quận 4",
    contracts: 2,
    totalContracts: 6,
    revenue: 6000000,
    rating: 4.0,
    status: "Inactive",
    month: "2025-10",
  },
  {
    id: "S020",
    name: "Tran Thi T",
    area: "Quận 6",
    contracts: 4,
    totalContracts: 14,
    revenue: 8800000,
    rating: 4.3,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S021",
    name: "Le Van U",
    area: "Quận 8",
    contracts: 6,
    totalContracts: 20,
    revenue: 13000000,
    rating: 4.9,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S022",
    name: "Pham Thi V",
    area: "Quận 10",
    contracts: 3,
    totalContracts: 9,
    revenue: 9200000,
    rating: 4.2,
    status: "Active",
    month: "2025-10",
  },
  {
    id: "S023",
    name: "Hoang Van W",
    area: "Quận 11",
    contracts: 5,
    totalContracts: 16,
    revenue: 11800000,
    rating: 4.6,
    status: "Active",
    month: "2025-10",
  },
];
export type TaskStepStatus = "pending" | "inProgress" | "done";

export interface TaskStep {
  id: number;
  title: string; // ví dụ: "Verify onboarding documents"
  description?: string; // chi tiết bước
  status: TaskStepStatus;
  documents?: string[]; // nếu step có document cần check
  tenantRequests?: string[]; // nếu step có yêu cầu tìm khách thuê
}

export interface Task {
  id: number;
  mallName: string;
  location: string;
  manager: string;
  assignedTo: string; // staff phụ trách
  steps: TaskStep[]; // các step của task
}
export const tasksData: Task[] = [
  {
    id: 1,
    mallName: "Mall A",
    location: "123 Street, District 1, HCM",
    manager: "Manager A",
    assignedTo: "staff1",
    steps: [
      {
        id: 1,
        title: "Onboarding review",
        status: "done",
        documents: [
          "Business License.pdf",
          "Floor Plan.pdf",
          "Mall Info Form.pdf",
        ],
        description:
          "Kiểm tra đầy đủ giấy tờ khởi tạo (onboarding) và xác minh thông tin mall.",
      },
      {
        id: 2,
        title: "On-site verification",
        status: "inProgress",
        description:
          "Đến thực địa để kiểm tra hiện trạng, đối chiếu sơ đồ và xác nhận thông tin với ban quản lý mall.",
      },
      {
        id: 3,
        title: "Update mall info",
        status: "pending",
        description:
          "Nếu có sai sót hoặc thông tin thiếu, tiến hành cập nhật lại dữ liệu mall trên hệ thống.",
      },
      {
        id: 4,
        title: "Lease & brand assignment",
        status: "pending",
        tenantRequests: ["Need 3 shops for Brand X", "1 shop for Brand Y"],
        description:
          "Hoàn thiện hợp đồng thuê và phân bổ gian hàng cho các brand quan tâm.",
      },
    ],
  },
  {
    id: 2,
    mallName: "Mall B",
    location: "456 Avenue, Thu Duc City, HCM",
    manager: "Manager B",
    assignedTo: "staff2",
    steps: [
      {
        id: 1,
        title: "Onboarding review",
        status: "done",
        documents: ["Business License.pdf", "Floor Plan.pdf"],
        description: "Đã xác nhận đầy đủ giấy phép và bản vẽ mặt bằng.",
      },
      {
        id: 2,
        title: "On-site verification",
        status: "done",
        description:
          "Đã hoàn tất kiểm tra thực địa và xác nhận đúng vị trí, layout.",
      },
      {
        id: 3,
        title: "Update mall info",
        status: "inProgress",
        description:
          "Đang chỉnh sửa thông tin một số khu vực gian hàng chưa khớp.",
      },
      {
        id: 4,
        title: "Lease & brand assignment",
        status: "pending",
        tenantRequests: ["Need 2 shops for Brand Z"],
        description: "Đang chuẩn bị ký hợp đồng với Brand Z, dự kiến tuần tới.",
      },
    ],
  },
  {
    id: 3,
    mallName: "Mall C",
    location: "789 Boulevard, District 7, HCM",
    manager: "Manager C",
    assignedTo: "staff3",
    steps: [
      {
        id: 1,
        title: "Onboarding review",
        status: "done",
        documents: ["Business License.pdf"],
        description: "Giấy phép hợp lệ, đang chờ sơ đồ mặt bằng bổ sung.",
      },
      {
        id: 2,
        title: "On-site verification",
        status: "pending",
        description:
          "Chưa tiến hành kiểm tra thực địa, dự kiến trong tuần này.",
      },
      {
        id: 3,
        title: "Update mall info",
        status: "pending",
        description: "Chưa có cập nhật thông tin.",
      },
      {
        id: 4,
        title: "Lease & brand assignment",
        status: "pending",
        tenantRequests: [],
        description: "Chưa đến giai đoạn tìm brand thuê.",
      },
    ],
  },
  {
    id: 4,
    mallName: "Mall D",
    location: "12 Nguyen Hue, District 1, HCM",
    manager: "Manager D",
    assignedTo: "staff4",
    steps: [
      {
        id: 1,
        title: "Onboarding review",
        status: "done",
        documents: ["Business License.pdf", "Mall Info Form.pdf"],
        description: "Hoàn tất bước onboarding.",
      },
      {
        id: 2,
        title: "On-site verification",
        status: "done",
        description: "Đã thực địa và kiểm tra thực tế.",
      },
      {
        id: 3,
        title: "Update mall info",
        status: "done",
        description: "Đã cập nhật thông tin đầy đủ trên hệ thống.",
      },
      {
        id: 4,
        title: "Lease & brand assignment",
        status: "inProgress",
        tenantRequests: ["Brand T - 5 kiosks", "Brand U - 2 stores"],
        description:
          "Đang thương lượng hợp đồng giữa mall và các brand tiềm năng.",
      },
    ],
  },
  {
    id: 5,
    mallName: "Mall E",
    location: "55 Tran Hung Dao, District 5, HCM",
    manager: "Manager E",
    assignedTo: "staff5",
    steps: [
      {
        id: 1,
        title: "Onboarding review",
        status: "done",
        documents: ["Business License.pdf", "Mall Info Form.pdf"],
        description: "Đã kiểm duyệt hồ sơ khởi tạo thành công.",
      },
      {
        id: 2,
        title: "On-site verification",
        status: "done",
        description: "Đã hoàn tất thực địa, không có sai lệch thông tin.",
      },
      {
        id: 3,
        title: "Update mall info",
        status: "done",
        description: "Không cần chỉnh sửa thêm.",
      },
      {
        id: 4,
        title: "Lease & brand assignment",
        status: "done",
        tenantRequests: [
          "Brand A - 2 units signed",
          "Brand B - 1 pending confirmation",
        ],
        description:
          "Đã ký hợp đồng với Brand A, Brand B đang chờ xác nhận cuối.",
      },
    ],
  },
];
