import { Users, Building2, Clock, FileCheck } from "lucide-react";
// Mock data
export const stats = [
  {
    label: "Tổng số TTTM/Thương hiệu đang hoạt động",
    value: "156",
    change: "+12%",
    icon: Building2,
    color: "bg-blue-500",
  },
  {
    label: "Tổng số nhân viên đang hoạt động",
    value: "24",
    change: "+3",
    icon: Users,
    color: "bg-green-500",
  },
  {
    label: "Tổng số yêu cầu xác thực đang chờ",
    value: "8",
    change: "-2",
    icon: Clock,
    color: "bg-yellow-500",
  },
  {
    label: "Tổng số hợp đồng trong tháng",
    value: "45",
    change: "+18%",
    icon: FileCheck,
    color: "bg-purple-500",
  },
];

export const mallsBrands = [
  {
    id: 1,
    name: "Vincom Center",
    type: "Mall",
    location: "District 1, HCMC",
    staff: "Nguyen Van A",
    status: "active",
    contracts: 5,
  },
  {
    id: 2,
    name: "Starbucks",
    type: "Brand",
    location: "Multiple",
    staff: "Tran Thi B",
    status: "active",
    contracts: 12,
  },
  {
    id: 3,
    name: "Lotte Mart",
    type: "Mall",
    location: "District 7, HCMC",
    staff: "Nguyen Van A",
    status: "active",
    contracts: 8,
  },
  {
    id: 4,
    name: "The Coffee House",
    type: "Brand",
    location: "Nationwide",
    staff: "Le Van C",
    status: "inactive",
    contracts: 3,
  },
];

export const areaAssignments = [
  {
    area: "Ho Chi Minh City",
    staff: ["Nguyen Van A", "Pham Van E"],
    malls: 45,
    brands: 67,
  },
  { area: "Hanoi", staff: ["Tran Thi B"], malls: 32, brands: 54 },
  { area: "Da Nang", staff: ["Le Van C"], malls: 18, brands: 28 },
  { area: "Can Tho", staff: ["Pham Thi D"], malls: 12, brands: 19 },
];
export const pendingVerifications = [
  {
    id: 1,
    name: "Vincom Center",
    type: "Mall",
    location: "District 1, HCMC",
    date: "2025-10-12",
    staff: "Nguyen Van A",
    status: "Pending",
  },
  {
    id: 2,
    name: "Starbucks",
    type: "Brand",
    location: "District 3, HCMC",
    date: "2025-10-13",
    staff: "Tran Thi B",
    status: "Pending",
  },
  {
    id: 3,
    name: "Aeon Mall",
    type: "Mall",
    location: "District 7, HCMC",
    date: "2025-10-14",
    staff: "Le Van C",
    status: "Approved",
  },
  {
    id: 4,
    name: "The Coffee House",
    type: "Brand",
    location: "District 5, HCMC",
    staff: null,
    date: "2025-10-15",
    status: "Rejected",
  },
];

export const staffPerformance = [
  {
    id: 1,
    name: "Nguyen Van A",
    area: "HCMC",
    contracts: 12,
    revenue: "450M VND",
    rating: 4.8,
  },
  {
    id: 2,
    name: "Tran Thi B",
    area: "HCMC",
    contracts: 15,
    revenue: "520M VND",
    rating: 4.9,
  },
  {
    id: 3,
    name: "Le Van C",
    area: "HCMC",
    contracts: 8,
    revenue: "280M VND",
    rating: 4.5,
  },
];
export const monthlyContractsData = [
  { month: "Jan", contracts: 5, revenue: 450 },
  { month: "Feb", contracts: 8, revenue: 600 },
  { month: "Mar", contracts: 12, revenue: 900 },
  { month: "Apr", contracts: 7, revenue: 520 },
  { month: "May", contracts: 10, revenue: 750 },
  { month: "Jun", contracts: 15, revenue: 1100 },
];

export const quarterlyContractsData = [
  { quarter: "Q1", contracts: 25, revenue: 1950 },
  { quarter: "Q2", contracts: 32, revenue: 2400 },
  { quarter: "Q3", contracts: 34, revenue: 2550 },
  { quarter: "Q4", contracts: 29, revenue: 2100 },
];
export const matchingData = [
  {
    id: "1",
    mallName: "Vincom Center",
    brandName: "Nike",
    location: "HCM",
    matchScore: 85,
    date: "2025-10-15",
  },
  {
    id: "2",
    mallName: "AEON Mall",
    brandName: "Adidas",
    location: "HCM",
    matchScore: 72,
    date: "2025-10-14",
  },
  {
    id: "3",
    mallName: "Takashimaya",
    brandName: "Puma",
    location: "HCM",
    matchScore: 90,
    date: "2025-10-13",
  },
  {
    id: "4",
    mallName: "Vincom Mega Mall",
    brandName: "Reebok",
    location: "HCM",
    matchScore: 78,
    date: "2025-10-12",
  },
];
export const defaultWeights = {
  location: 0.4,
  brandPopularity: 0.3,
  mallTraffic: 0.2,
  rentalCost: 0.1,
};
interface Contract {
  coordination_contract_id: string;
  starting_date: string;
  ending_date: string;
  commision_percent: number;
  mall_owner: string;
  upload_by: string;
  create_at: string;
  terminated_at?: string;
  status: "Active" | "Pending" | "Terminated";
  update_by?: string;
  note?: string;
  contract_url?: string;
}
export const contracts: Contract[] = [
  {
    coordination_contract_id: "CT001",
    starting_date: "2024-06-01",
    ending_date: "2025-06-01",
    commision_percent: 10,
    mall_owner: "Vincom Đồng Khởi",
    upload_by: "Admin",
    create_at: "2024-06-01",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT002",
    starting_date: "2024-09-01",
    ending_date: "2025-09-01",
    commision_percent: 8,
    mall_owner: "Aeon Mall Tân Phú",
    upload_by: "Admin",
    create_at: "2024-09-01",
    status: "Pending",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT003",
    starting_date: "2024-10-15",
    ending_date: "2025-10-15",
    commision_percent: 12,
    mall_owner: "Crescent Mall",
    upload_by: "Admin",
    create_at: "2024-10-15",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT004",
    starting_date: "2024-11-01",
    ending_date: "2025-11-01",
    commision_percent: 7,
    mall_owner: "Saigon Centre",
    upload_by: "Admin",
    create_at: "2024-11-01",
    status: "Terminated",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT005",
    starting_date: "2025-01-01",
    ending_date: "2026-01-01",
    commision_percent: 9,
    mall_owner: "Diamond Plaza",
    upload_by: "Admin",
    create_at: "2025-01-01",
    status: "Active",
    contract_url: "#",
  },
  // 15 record mới
  {
    coordination_contract_id: "CT006",
    starting_date: "2025-02-01",
    ending_date: "2026-02-01",
    commision_percent: 11,
    mall_owner: "Lotte Mart Quận 7",
    upload_by: "Admin",
    create_at: "2025-02-01",
    status: "Pending",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT007",
    starting_date: "2025-03-15",
    ending_date: "2026-03-15",
    commision_percent: 6,
    mall_owner: "Takashimaya",
    upload_by: "Admin",
    create_at: "2025-03-15",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT008",
    starting_date: "2025-04-01",
    ending_date: "2026-04-01",
    commision_percent: 8,
    mall_owner: "Vivo City",
    upload_by: "Admin",
    create_at: "2025-04-01",
    status: "Terminated",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT009",
    starting_date: "2025-05-10",
    ending_date: "2026-05-10",
    commision_percent: 9,
    mall_owner: "Aeon Mall Bình Tân",
    upload_by: "Admin",
    create_at: "2025-05-10",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT010",
    starting_date: "2025-06-01",
    ending_date: "2026-06-01",
    commision_percent: 10,
    mall_owner: "Saigon Paragon",
    upload_by: "Admin",
    create_at: "2025-06-01",
    status: "Pending",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT011",
    starting_date: "2025-06-15",
    ending_date: "2026-06-15",
    commision_percent: 7,
    mall_owner: "Bitexco Tower Mall",
    upload_by: "Admin",
    create_at: "2025-06-15",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT012",
    starting_date: "2025-07-01",
    ending_date: "2026-07-01",
    commision_percent: 12,
    mall_owner: "Vincom Mega Mall Thảo Điền",
    upload_by: "Admin",
    create_at: "2025-07-01",
    status: "Terminated",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT013",
    starting_date: "2025-07-20",
    ending_date: "2026-07-20",
    commision_percent: 9,
    mall_owner: "The Garden Mall",
    upload_by: "Admin",
    create_at: "2025-07-20",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT014",
    starting_date: "2025-08-01",
    ending_date: "2026-08-01",
    commision_percent: 8,
    mall_owner: "Vincom Center Landmark 81",
    upload_by: "Admin",
    create_at: "2025-08-01",
    status: "Pending",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT015",
    starting_date: "2025-08-15",
    ending_date: "2026-08-15",
    commision_percent: 10,
    mall_owner: "Crescent Mall 2",
    upload_by: "Admin",
    create_at: "2025-08-15",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT016",
    starting_date: "2025-09-01",
    ending_date: "2026-09-01",
    commision_percent: 11,
    mall_owner: "AEON Mall Long Biên",
    upload_by: "Admin",
    create_at: "2025-09-01",
    status: "Terminated",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT017",
    starting_date: "2025-09-15",
    ending_date: "2026-09-15",
    commision_percent: 7,
    mall_owner: "Vincom Plaza Nguyễn Chí Thanh",
    upload_by: "Admin",
    create_at: "2025-09-15",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT018",
    starting_date: "2025-10-01",
    ending_date: "2026-10-01",
    commision_percent: 9,
    mall_owner: "Indochina Plaza",
    upload_by: "Admin",
    create_at: "2025-10-01",
    status: "Pending",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT019",
    starting_date: "2025-10-20",
    ending_date: "2026-10-20",
    commision_percent: 10,
    mall_owner: "Parkson Saigon Tourist",
    upload_by: "Admin",
    create_at: "2025-10-20",
    status: "Active",
    contract_url: "#",
  },
  {
    coordination_contract_id: "CT020",
    starting_date: "2025-11-01",
    ending_date: "2026-11-01",
    commision_percent: 8,
    mall_owner: "Vincom Plaza Cộng Hòa",
    upload_by: "Admin",
    create_at: "2025-11-01",
    status: "Terminated",
    contract_url: "#",
  },
];
